### ISSUE TITLE
Merge Sort code with algorithm

### ISSUE THREAD

**Issue by JohnJordan0098** [JohnJordan0098/Data-Structures-Algos#1]
**MERGE SORT:**
So, in this issue for beginners you just have to add a merge sort code along with its algorithm .That's it
So, for beginners it will help you for getting started in open source contributing

**Comment by aniket2003** [comment]
@JohnJordan0098 I would like to work on this , since I am efficient at Algorithms . Could you please assign me .

**Comment by JohnJordan0098** [comment]
> @JohnJordan0098 I would like to work on this , since I am efficient at Algorithms . Could you please assign me .
You could do in next issue Sorry I have assigned at random I will create a next issue and will assigned it to you.
