### ISSUE TITLE
Reverse a linked list

### ISSUE THREAD

**Issue by JohnJordan0098** [JohnJordan0098/Data-Structures-Algos#11]
Given pointer to the head node of a linked list, the task is to reverse the linked list. We need to reverse the list by changing the links between nodes.
Input: Head of following linked list 
1->2->3->4->NULL 
Output: Linked list should be changed to, 
4->3->2->1->NULL

Input: Head of following linked list 
1->2->3->4->5->NULL 
Output: Linked list should be changed to, 
5->4->3->2->1->NULL

**Comment by lil-Ribhav-Bhatt1012** [comment]
Hey can I do this a I am good at data structures

**Comment by JohnJordan0098** [comment]
okay!!
