### ISSUE TITLE
Leetcode 6 Zigzag Conversion

### ISSUE THREAD

**Issue by AbhinavRajputEXE** [JohnJordan0098/Data-Structures-Algos#15]
The string "PAYPALISHIRING" is written in a zigzag pattern on a given number of rows like this: (you may want to display this pattern in a fixed font for better legibility)

**Comment by AbhinavRajputEXE** [comment]
please assign this to me

**Comment by JohnJordan0098** [comment]
no problrm

**Comment by JohnJordan0098** [comment]
looks good to me

**Comment by JohnJordan0098** [comment]
nice work!
